name: endless_runner
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+20

environment:
  sdk: ^3.0.0

dependencies:
  flame: ^1.10.1
  flutter:
    sdk: flutter

  firebase_auth: ^4.17.8
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  dart_jsonwebtoken: ^2.13.0
  google_wallet: ^0.1.0
  battery_plus: ^5.0.3
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  flame_audio: ^2.1.3
  go_router: ^12.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  nes_ui: ^0.10.0
  google_fonts: 6.1.0
  logging: ^1.2.0
  envied: ^0.5.3
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  mocktail: ^1.0.3

dev_dependencies:
  flame_test: ^1.14.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3
  build_runner: ^2.4.8
  flutter_gen_runner:
  envied_generator: ^0.5.3
  msix: ^3.16.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/json/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

msix_config:
  display_name: Whaleys Bins Waste Sorting
  msix_version: 1.0.1.0
