// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbHpMaRt7v1fCvjkmI0F01N6POgiISf6s',
    appId: '1:846503316572:web:fcf6537a109f0fee0f2a99',
    messagingSenderId: '846503316572',
    projectId: 'whaley-adaf8',
    authDomain: 'whaley-adaf8.firebaseapp.com',
    storageBucket: 'whaley-adaf8.appspot.com',
    measurementId: 'G-XNWSWPE9V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBabus4hWBuccM7_xj7tTR9D-p_FOsnjJs',
    appId: '1:846503316572:android:707b0109f47031c80f2a99',
    messagingSenderId: '846503316572',
    projectId: 'whaley-adaf8',
    storageBucket: 'whaley-adaf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0jVi0Yo9Io3CrGfwFcrWN3DWh5QOz4Bc',
    appId: '1:846503316572:ios:d2cde799912031010f2a99',
    messagingSenderId: '846503316572',
    projectId: 'whaley-adaf8',
    storageBucket: 'whaley-adaf8.appspot.com',
    iosBundleId: 'studio.happycode.whaley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0jVi0Yo9Io3CrGfwFcrWN3DWh5QOz4Bc',
    appId: '1:846503316572:ios:989ec3111395bd0c0f2a99',
    messagingSenderId: '846503316572',
    projectId: 'whaley-adaf8',
    storageBucket: 'whaley-adaf8.appspot.com',
    iosBundleId: 'studio.happycode.whaley.macos',
  );
}
